/**
 * WordPress dependencies
 */
const [
	defaultScriptConfig,
] = require( '@wordpress/scripts/config/webpack.config' );

/**
 * External dependencies
 */
const RemoveEmptyScriptsPlugin = require( 'webpack-remove-empty-scripts' );
const path = require( 'path' );

/**
 * Define your script entrypoints here.
 *
 * Each entrypoint will be built into its own enqueuable asset.
 *
 * Blocks are handled separately via the `--package-manifest` flag in @wordpress/scripts
 */
const scriptEntries = {
	admin: path.resolve( process.cwd(), 'src/admin/index.ts' ),
};

const scriptConfig = {
	...defaultScriptConfig,
	entry: {
		// WordPress stores them in a function.
		...defaultScriptConfig.entry(),
		...scriptEntries,
	},

	plugins: [
		// Include WP's plugin config.
		...defaultScriptConfig.plugins,

		// Removes the empty `.js` files generated by webpack but
		// sets it after WP has generated its `*.asset.php` file.
		new RemoveEmptyScriptsPlugin( {
			stage: RemoveEmptyScriptsPlugin.STAGE_AFTER_PROCESS_PLUGINS,
		} ),
	],
};

module.exports = [ scriptConfig ];
