name: Reusable Build

on:
  workflow_call:
    inputs:
      php-version:
        required: true
        type: string
      artifact-name:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          show-progress: ${{ runner.debug == '1' && 'true' || 'false' }}
          persist-credentials: false

      - name: Set up PHP
        uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # v2.37.1
        with:
          php-version: ${{ inputs.php-version }}
          coverage: none

      - name: Install Composer dependencies
        uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # v4.0.0
        with:
          composer-options: '--no-dev --optimize-autoloader'

      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install npm dependencies
        run: npm ci

      - name: Build plugin for release
        run: npm run build

      - name: Generate Translation files
        run: |
          curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
          php wp-cli.phar i18n make-pot . ./languages/rtcamp-publish-with-ai.pot --domain=rtcamp-publish-with-ai --include="*.php,inc,framework,src,templates" --exclude="assets,build,build-apps,node_modules,tests,vendor"

      - name: Create plugin zip
        run: npm run plugin-zip

      - name: Upload plugin zip artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{ inputs.artifact-name }}
          path: rtcamp-publish-with-ai.zip
          if-no-files-found: error
