name: Plugin Check (PCP)

on:
  workflow_call:
    inputs:
      wp-version:
        description: 'WordPress version to test against'
        required: false
        type: string
        default: 'latest'

permissions:
  contents: read
  pull-requests: write

jobs:
  plugin-check:
    name: Plugin Check (PCP)
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          show-progress: ${{ runner.debug == '1' && 'true' || 'false' }}

      - name: Run WordPress Plugin Check
        uses: wordpress/plugin-check-action@18573eb38f13543484a1f095672dae3849a4fbb0 # v1
        with:
          build-dir: './'
          wp-version: ${{ inputs.wp-version }}
