name: Run JS Lint

on:
  workflow_call:

permissions: {}

jobs:
  lint-js:
    name: JS Lint & TypeScript
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          show-progress: ${{ runner.debug == '1' && 'true' || 'false' }}
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install npm dependencies
        run: npm ci

      - name: Run ESLint
        id: eslint
        continue-on-error: true
        run: npm run lint:js

      - name: Run TypeScript check
        id: typescript
        continue-on-error: true
        run: npm run lint:js:types

      - name: Run Stylelint
        id: stylelint
        continue-on-error: true
        run: npm run lint:css

      - name: Run Prettier check
        id: prettier
        continue-on-error: true
        run: npm run format -- --check

      - name: Check for errors
        if: ${{ steps.eslint.outcome == 'failure' || steps.typescript.outcome == 'failure' || steps.prettier.outcome == 'failure' || steps.stylelint.outcome == 'failure' }}
        run: |
          echo "One or more checks failed. See logs above for details."
          exit 1
